import { Check, Copy } from "lucide-react";
import * as React from "react";

import { cn } from "@/lib/cn";

type Client = {
  id: string;
  label: string;
  file?: string;
  note?: string;
  build: (url: string, key: string) => string;
};

// Formats verified against each tool's official MCP docs (Grok is a best-effort stdio bridge —
// its remote-HTTP schema isn't officially documented).
const CLIENTS: Client[] = [
  {
    id: "claude",
    label: "Claude Code",
    note: "Run in your terminal. Add --scope user to make it global.",
    build: (u, k) => `claude mcp add --transport http agentledger ${u} --header "X-API-Key: ${k}"`,
  },
  {
    id: "cursor",
    label: "Cursor",
    file: "~/.cursor/mcp.json",
    build: (u, k) => JSON.stringify({ mcpServers: { agentledger: { url: u, headers: { "X-API-Key": k } } } }, null, 2),
  },
  {
    id: "codex",
    label: "Codex",
    file: "~/.codex/config.toml",
    build: (u, k) => `[mcp_servers.agentledger]\nurl = "${u}"\nhttp_headers = { "X-API-Key" = "${k}" }`,
  },
  {
    id: "opencode",
    label: "opencode",
    file: "opencode.json",
    build: (u, k) =>
      JSON.stringify(
        {
          $schema: "https://opencode.ai/config.json",
          mcp: { agentledger: { type: "remote", url: u, enabled: true, headers: { "X-API-Key": k } } },
        },
        null,
        2,
      ),
  },
  {
    id: "grok",
    label: "Grok CLI",
    file: ".grok/settings.json",
    note: "Grok's remote-MCP format isn't officially documented; this stdio bridge (mcp-remote) works reliably.",
    build: (u, k) =>
      JSON.stringify(
        { mcpServers: { agentledger: { command: "npx", args: ["-y", "mcp-remote", u, "--header", `X-API-Key: ${k}`] } } },
        null,
        2,
      ),
  },
];

/** Autogenerated MCP install commands for the just-created key, per coding tool. */
export function McpInstall({ apiKey }: { apiKey: string }) {
  const origin = typeof window !== "undefined" ? window.location.origin : "";
  const url = `${origin}/api/mcp`;
  const [sel, setSel] = React.useState("claude");
  const [copied, setCopied] = React.useState(false);
  const client = CLIENTS.find((c) => c.id === sel)!;
  const snippet = client.build(url, apiKey);

  return (
    <div className="mt-3 rounded-[11px] border border-line-2 bg-surface-2 p-3">
      <div className="mb-2 font-mono text-[10px] uppercase tracking-wide text-faint">Connect an agent · MCP</div>
      <div className="mb-2 flex flex-wrap gap-1.5">
        {CLIENTS.map((c) => (
          <button
            key={c.id}
            onClick={() => {
              setSel(c.id);
              setCopied(false);
            }}
            className={cn(
              "rounded-md border px-2 py-1 text-[11px] transition-colors",
              sel === c.id ? "border-accent/50 bg-surface-3 text-fg" : "border-line-2 text-muted hover:text-fg-2",
            )}
          >
            {c.label}
          </button>
        ))}
      </div>
      {client.file && <div className="mb-1 font-mono text-[10.5px] text-muted-2">{client.file}</div>}
      <div className="relative">
        <pre className="max-h-56 overflow-auto rounded-md border border-line-2 bg-surface px-2.5 py-2 pr-10 font-mono text-[10.5px] leading-relaxed text-fg-2">
          {snippet}
        </pre>
        <button
          onClick={() => {
            navigator.clipboard.writeText(snippet);
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
          }}
          className="absolute right-1.5 top-1.5 rounded-md border border-line-2 bg-surface-3 p-1.5 text-muted hover:text-fg"
          title="Copy"
        >
          {copied ? <Check size={13} className="text-accent" /> : <Copy size={13} />}
        </button>
      </div>
      {client.note && <p className="mt-1.5 text-[10.5px] text-faint">{client.note}</p>}
      <p className="mt-1 text-[10.5px] text-faint">
        The URL must be reachable from where the agent runs — <span className="font-mono">{url}</span>
      </p>
    </div>
  );
}
